POST http://localhost:5001/api/auth/register/seller
Content-Type: application/json

{
   "name":"kebede",
   "email":"kebede_gmail.com",
   "password":"1234",
   "phone":"0701010101"
}

###
POST http://localhost:5001/api/auth/signin
Content-Type: application/json

{
   "email":"kebede@gmail.com",
   "password":"1234"
}